### ISSUE TITLE
dgarland1 securitycenter script issues

### ISSUE THREAD

**Issue by heathergay** [tenable/pyTenable#125]
Hey, guys NOOB here in need of assistance. I am working off the dgarland asset dump script using pytenable and I am stuck (reference below). I am being prompted for credentials, host and export file now but I am getting the following afterwards. Not sure why I am unable to pull the asset list but hopefully someone can help. I am an admin in security center FYI.

C:\SecurityCenter2\Scripts\python.exe C:/SecurityCenter2/Asset/GetAsset.py
2019-06-06 15:38:49,503 - pyLogging - INFO - Running on Python version 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
2019-06-06 15:38:50,531 - pyLogging - INFO - Getting list of data from SecurityCenter
2019-06-06 15:38:51,393 - pyLogging - ERROR - Failed to get data from SecurityCenter
2019-06-06 15:38:51,394 - pyLogging - ERROR - Likely cause is the query is malformed
Traceback (most recent call last):
  File "C:/SecurityCenter2/Asset/GetAsset.py", line 172, in getAssetData
    'fields': 'id,name,description,viewableIPs'
  File "C:\SecurityCenter2\lib\site-packages\securitycenter\base.py", line 88, in get
    return self._resp_error_check(resp)
  File "C:\SecurityCenter2\lib\site-packages\securitycenter\sc5.py", line 31, in _resp_error_check
    raise APIError(d['error_code'], d['error_msg'])
securitycenter.base.APIError: '[104]: Unable to retrieve the list of managed assets for this user during Asset GET.\nUnable to retrieve ip list for asset #172 (user #52 repository #5).\nCould not locate ip file /opt/sc/orgs/1/assets/0/5/172.ipd.\n'
2019-06-06 15:38:51,398 - pyLogging - INFO - Exiting script due to an error

Process finished with exit code 0

References
https://github.com/DGarland1/SecurityCenterScripts/blob/master/Asset/GetAssets.py

**Comment by SteveMcGrath** [comment]
the DGarland1 script is using pySecurityCenter and not pyTenable. Note the line below:

https://github.com/DGarland1/SecurityCenterScripts/blob/master/Asset/GetAssets.py#L159

Secondly, the issue appears to be a SC-specific issue, not an API one.  Notably that asset list id 172 appears to be broken.

As this isn't a pyTenable-specific issue, please direct this to the community portal.
