### ISSUE TITLE
schedule(scan_id, enabled) API is not working

### ISSUE THREAD

**Issue by zidhumenon** [tenable/pyTenable#188]
**Describe the bug**
when i make a call to this schedule API to enable the schedule for a scanid it gives me **{"error":"No schedule to configure"}** 

**To Reproduce**
1. Go to `https://pytenable.readthedocs.io/en/latest/io.html`
2. Call `tio.scans.schedule(scanid, True)`
3. See error
```
PUT https://cloud.tenable.com/scans/******/schedule >> *******:400 {"error":"No schedule to configure"}
Traceback (most recent call last):
  File "/Users/PycharmProjects/testing/TenableIOSDK.py", line 147, in <module>
    schedulescan()
  File "/Users/PycharmProjects/testing/TenableIOSDK.py", line 118, in schedulescan
    tio.scans.schedule(******,enabled=True)
  File "/Users/testing/lib/python3.7/site-packages/tenable/io/scans.py", line 902, in schedule
    'enabled': self._check('enabled', enabled, bool)}).json()
  File "/Users/testing/lib/python3.7/site-packages/tenable/base.py", line 547, in put
    return self._request('PUT', path, **kwargs)
  File "/Users/testing/lib/python3.7/site-packages/tenable/base.py", line 482, in _request
    raise self._error_codes[status](resp)
tenable.errors.InvalidInputError: *******:400 {"error":"No schedule to configure"}
```

**Expected behavior**
It should enable the schedule option in configure section 

**System Information (please complete the following information):**
 - OS: MacOS 
 - Architecture: 64bit
 - Version: 10.14.6
 - Memory: 16GB

**Comment by zidhumenon** [comment]
Somehow enabling and disabling schedule option is working in schedule(scan_id, enabled) API.
Not sure what was the issue last time. so i am closing this issue!! Thanks!
