### ISSUE TITLE
Invoking TenableIO API with incorrect url causes python traceback.

### ISSUE THREAD

**Issue by cheburakshu** [tenable/pyTenable#203]
**Describe the bug**

While invoking tenable API like below with an invalid url, I encountered the below error during testing. Still returns a HTTP 500, which is good and is not a blocker, but wanted to let you know. Thanks.

```
tio = TenableIO(url=‘invalid_url’, access_key=‘good_key’, secret_key=‘good_secret_key’)
tio.session.details()
```

```
[ERROR   ][raas.utils.rpc:183 ][Webserver:12155] local variable 'resp' referenced before assignment
Traceback (most recent call last):
  File "/app/raas/raas/utils/rpc.py", line 233, in process_rpc_request_within_its_own_context
    response.ret = await resolve_coroutine(rpc_func(*rpc_args, **rpc_kwargs))
  File "/app/raas/raas/utils/coro.py", line 19, in resolve_coroutine
    result = await result
  File "/home/raas/.local/lib/python3.6/site-packages/pop/contract.py", line 230, in __call__
    ret = await self.contract_functions["call"][0](contract_context)
  File "/app/raas/raas/mods/rpc/vman.py", line 1726, in save_connector
    connector_params=connector_params)
  File "/home/raas/.local/lib/python3.6/site-packages/pop/contract.py", line 222, in __call__
    return await self.func(*args, **kwargs)
  File "/app/raas/raas/mods/vman/connector.py", line 30, in save_connector
    retries=0)
  File "/app/raas/raas/utils/tenable.py", line 37, in authenticate
    session = tio.session.details()
  File "/home/raas/.local/lib/python3.6/site-packages/tenable/io/session.py", line 62, in details
    return self._api.get('session').json()
  File "/home/raas/.local/lib/python3.6/site-packages/tenable/base.py", line 543, in get
    return self._request('GET', path, **kwargs)
  File "/home/raas/.local/lib/python3.6/site-packages/tenable/base.py", line 525, in _request
    raise RetryError(resp, retries)
UnboundLocalError: local variable 'resp' referenced before assignment
[DEBUG   ][raas.utils.rpc:284 ][Webserver:12155] Processed RPC request(191848699955380). Response: {'riq': 191848699955380, 'ret': None, 'error': {'code': 5000, 'message': 'Internal Server Error. Please check the raas server logs.'}, 'warnings': []}
```
**To Reproduce**
2. Call  '....'
3. Do '....'

**Expected behavior**
Return a meaningful error.

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. MacOS]
 - Architecture [e.g. 64bit, 32bit]
 - Version [e.g. 2.7.9]
 - Memory [e.g. 4G]

**Additional context**

**Comment by SteveMcGrath** [comment]
Corrected in 1.1.3 https://github.com/tenable/pyTenable/commit/93b4a1eadc3491313b85020aacca0866fd6bdb31
