### ISSUE TITLE
Retrieving scan details using scans.details(scan_id) fails for scans created with select plugins enabled

### ISSUE THREAD

**Issue by ravindrarajaram** [tenable/pyTenable#254]
**Describe the bug**
Retrieving scan details using scans.details(scan_id) fails for scans created with select plugins enabled

**To Reproduce**
1. Create a new scan using 'Advanced Network Scan' template
2. Under the 'Plugins' tab, disable all plugins
3. Now enable any random plugins in any of the plugin families
For ex: Under the 'Databases' plugin family, enable ANY plugin
4. Fill up other required scan details (scan name, scanner, ip address etc,.)
5. Save the scan and copy the scan id

Now use the pyTenable SDK retrieve the scan details of the scan id; fails with the following stack trace (P.S. Ran this with a python virtual env)

2020-12-07 12:27:24,061 - ERROR - __init__ - errors.py:29 - GET https://cloud.tenable.com/editor/xxxx/families/20 >> 23ea3d02b2e87a05878b872b49c1ae08:404 {"error":"The requested file was not found"}
Traceback (most recent call last):
  File "tenableapi.py", line 1148, in <module>
    scanJob=tapi.getScan(xxxx)
  File "tenableapi.py", line 739, in getScan
    scanDetails=self.tio.scans.details(scanid)
  File "/home/user/project/lib/python3.6/site-packages/tenable/io/scans.py", line 481, in details
    return self._api.editor.details('scan', scan_id)
  File "/home/user/project/lib/python3.6/site-packages/tenable/io/editor.py", line 340, in details
    editor['plugins']['families'], id)
  File "/home/user/project/lib/python3.6/site-packages/tenable/io/editor.py", line 117, in parse_plugins
    id=id, fam=families[family]['id'])).json()['plugins']
  File "/home/user/project/lib/python3.6/site-packages/tenable/base/v1.py", line 560, in get
    return self._request('GET', path, **kwargs)
  File "/home/user/project/lib/python3.6/site-packages/tenable/base/v1.py", line 531, in _request
    raise self._error_codes[status](resp)
tenable.errors.NotFoundError: 23ea3d02b2e87a05878b872b49c1ae08:404 {"error":"The requested file was not found"}

**Expected behavior**
Expected to retrieve the details of the scan id successfully

**Screenshots**

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture 64bit
 - pyTenable version  1.2.5
 - Python 3.6.9
 - Memory 8G

**Additional context**
None

**Comment by ravindrarajaram** [comment]
Update:
The same bug affects retrieving policy details for such policies where only select plugins are enabled.
For ex: 
editor.details('policy',policy_id)
This policy should have been created with only select plugins enabled.

**Comment by ravindrarajaram** [comment]
Created PR : https://github.com/tenable/pyTenable/pull/255
