### ISSUE TITLE
"AttributeError: 'Response' object has no attribute ..." When using `tenable.io.exports.vulns`

### ISSUE THREAD

**Issue by nzig** [tenable/pyTenable#520]
**Describe the bug**
Exception thrown in pyTenable in production. I am unable to reproduce locally, but have seen it in the logs twice.

**To Reproduce**
Don't know

**Stack Traces**
(When using the iterator returned by `tenable.io.exports.vulns`:
```
Traceback (most recent call last):
  ...
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/iterator.py", line 182, in next
    self._get_page()
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/iterator.py", line 148, in _get_page
    self._get_chunks()
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/iterator.py", line 132, in _get_chunks
    status = self._get_status()
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/iterator.py", line 77, in _get_status
    status.status
AttributeError: 'Response' object has no attribute 'status'
```

When calling `tenable.io.exports.vulns`:
```
Traceback (most recent call last):
  ...
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/api.py", line 448, in vulns
    return self._export('vulns', VulnExportSchema(), **kwargs)
  File "/opt/medigator/env/lib/python3.8/site-packages/tenable/io/exports/api.py", line 180, in _export
    export_uuid = self._api.post(f'{export_type}/export',
AttributeError: 'Response' object has no attribute 'export_uuid'
```

**System Information:**
 - OS: Ubuntu 18.04
 - Architecture: 64bit
 - pyTenable 1.4.3
 - Python 3.8

I suspect that this is caused by mishandling some kind of error response from the Tenable.io server.

**Comment by SteveMcGrath** [comment]
Is this happening often?  do you have the debug logs?

**Comment by nzig** [comment]
74 times in the last week. I'll try to get debug logs.

**Comment by nzig** [comment]
Here are the debug logs of the request:
```
DEBUG:tenable.io.TenableIO:Request: {"method": "POST", "url": "[https://cloud.tenable.com/vulns/export]()", "params": {}, "body": {"num_assets": 500, "filters": {"last_found": 1644840275, "severity": ["low", "medium", "high", "critical"], "state": ["open", "reopened", "fixed"]}}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:[https://cloud.tenable.com:443]() "POST [/vulns/export]() HTTP[/1.1]()" 200 54
```

I did some debugging, and it seems I was hitting the issue fixed in https://github.com/SteveMcGrath/restfly/commit/5d869a33117807d1dbca2264b72ac08f3ce7aa98. Upgrading restfly from 1.4.4 to 1.4.5 fixed the problem. Maybe the requirements for pyTenable should be updated to avoid the buggy version?

**Comment by SteveMcGrath** [comment]
Agreed, looping @tomeara into this as well.
