### ISSUE TITLE
NessusReportv2: UnicodeDecodeError with report from agent scan

### ISSUE THREAD

**Issue by Barnoux** [tenable/pyTenable#578]
**Describe the bug**
I got an UnicodeDecodeError when i'm using NessusReportv2 with a report from an agent scan.

**To Reproduce**
Nessus Manager command to the Nessus agent the scan that they have to do,
Tenable.sc import the result with an agent synchronation job,
The analyst download the agent scan report (eg:632.nessus) from the tenable.sc console,
The analyst launch the code bellow
```
#!python3
from tenable.reports import NessusReportv2
import re

def run():
    redur = re.compile('Scan duration : (\d+) sec')
    with open('632.nessus') as nessus_file:
        report = NessusReportv2(nessus_file)
        for item in report:
            if item['pluginID'] == 19506:
                res = redur.findall(item['plugin_output'])
                if len(res) > 0:
                    print('{} Took {} seconds to complete.'.format(item['host-ip'], res[0]))

if __name__ == '__main__':
    run()
```

**Expected behavior**
I expected to print all the duration that an agent scan took for each workstation.

The error:
```
PS C:\Users\barnoux\Développement\Python\Nessus> python .\speed_report.py
192.168.128.250 Took 5414 seconds to complete.
192.168.128.142 Took 6255 seconds to complete.
10.150.32.130 Took 7381 seconds to complete.
Traceback (most recent call last):
  File "C:\Users\barnoux\Développement\Python\Nessus\speed_report.py", line 16, in <module>                
    run()                                                                                                  
  File "C:\Users\barnoux\Développement\Python\Nessus\speed_report.py", line 9, in run                      
    for item in report:                                                                                    
  File "C:\Users\barnoux\pythonInstall\lib\site-packages\tenable\reports\nessusv2.py", line 47, in __next__
    return self.next()                                                                                     
  File "C:\Users\barnoux\pythonInstall\lib\site-packages\tenable\reports\nessusv2.py", line 81, in next    
    for event, elem in self._iter:                                                                         
  File "C:\Users\barnoux\pythonInstall\lib\xml\etree\ElementTree.py", line 1256, in iterator               
    data = source.read(16 * 1024)                                                                          
  File "C:\Users\barnoux\pythonInstall\lib\encodings\cp1252.py", line 23, in decode                        
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]                                      
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 12989: character maps to <undefined>
```

**System Information (please complete the following information):**
 - OS: Windows 10 (20H2)
 - Architecture: 64-bit
 - Python Version: 3.9
 - Memory: 6GB
 - IDE: PyCharm 2022.1.1

**Additional context**
I already check if lxml is correctly installed. And this error only happen with agent scan report.

**Comment by SteveMcGrath** [comment]
Couple of questions:

1. Have you attempted to specify the encoding when opening the file?

```python
with open('632.nessus', encoding='utf-8') as nessus_file:
```

2. Why download the report when the data is available via the API?

**Comment by Barnoux** [comment]
1. Oh i didn't try and it worked !
2. Do you mean the API with Tenable.sc or Nessus Manager ? I didn't try with Tenable.sc i will consider it in the futur.
