### ISSUE TITLE
can't import nessus

### ISSUE THREAD

**Issue by mrmathematica** [tenable/pyTenable#579]
```
$ pip install pytenable
Collecting pytenable
  Downloading pyTenable-1.4.6-py3-none-any.whl (406 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.0/407.0 kB 38.6 MB/s eta 0:00:00
Collecting python-dateutil>=2.6
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 41.1 MB/s eta 0:00:00
Collecting urllib3>=1.26.5
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 24.8 MB/s eta 0:00:00
Collecting defusedxml>=0.5.0
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting python-box>=4.0
  Downloading python_box-6.0.2-py3-none-any.whl (26 kB)
Collecting semver>=2.8.1
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting requests>=2.26
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 12.6 MB/s eta 0:00:00
Collecting restfly>=1.4.5
  Downloading restfly-1.4.6-py3-none-any.whl (24 kB)
Collecting typing-extensions>=4.0.1
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting marshmallow>=3.6
  Downloading marshmallow-3.15.0-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 kB 9.2 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 7.4 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.5.18.1-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.2/155.2 kB 27.6 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 12.3 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting arrow>=1.0.3
  Downloading arrow-1.2.2-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.0/64.0 kB 13.0 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 18.4 MB/s eta 0:00:00
Installing collected packages: urllib3, typing-extensions, six, semver, python-box, pyparsing, idna, defusedxml, charset-normalizer, certifi, requests, python-dateutil, packaging, marshmallow, arrow, restfly, pytenable
Successfully installed arrow-1.2.2 certifi-2022.5.18.1 charset-normalizer-2.0.12 defusedxml-0.7.1 idna-3.3 marshmallow-3.15.0 packaging-21.3 pyparsing-3.0.9 pytenable-1.4.6 python-box-6.0.2 python-dateutil-2.8.2 requests-2.27.1 restfly-1.4.6 semver-2.13.0 six-1.16.0 typing-extensions-4.2.0 urllib3-1.26.9
$ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tenable.nessus as nessus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/tenable/nessus/__init__.py", line 4, in <module>
    from .api import Nessus
  File "/tmp/venv/lib/python3.8/site-packages/tenable/nessus/api.py", line 38, in <module>
    from .agents import AgentsAPI
  File "/tmp/venv/lib/python3.8/site-packages/tenable/nessus/agents.py", line 16, in <module>
    from .iterators.pagination import PaginationIterator
ModuleNotFoundError: No module named 'tenable.nessus.iterators'

```
From pypi.org, pyTenable-1.4.6-py3-none-any.whl file (or pyTenable-1.4.6.tar.gz file) are missing tenable/nessus/iterators folde

Similar to #478 \_\_init\_\_.py is missing.

**Comment by mrmathematica** [comment]
From pypi.org, pyTenable-1.4.6-py3-none-any.whl file (or pyTenable-1.4.6.tar.gz file) are missing tenable/nessus/iterators folder

**Comment by mrmathematica** [comment]
Similar to  #478 __init__.py is missing.

**Comment by OtharSmirnow** [comment]
same issue here
