### ISSUE TITLE
Unable to export report in PDF format.

### ISSUE THREAD

**Issue by varamanikya** [tenable/pyTenable#604]
**Describe the bug**
I did not find a way to export the scan results in pdf format. when I see the code format pdf seems to be supported but when tried to execute, an Exception is thrown.

**To Reproduce**
>>> with open('example.pdf, 'wb') as fobj:
...     sc.scan_instances.export_scan(1,fobj,export_format='pdf')
... 
scap1_2export_format has value of pdf.  Expected one of ,v2
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tenable/sc/scan_instances.py", line 155, in export_scan
    'downloadType': self._check('export_format', export_format, str,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tenable/base/endpoint.py", line 85, in _check
    return check(name=name,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/restfly/utils.py", line 546, in check
    validate_normalized(obj, validate_choice_list, kwargs.get('choices'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/restfly/utils.py", line 474, in validate_normalized
    func(arg, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/restfly/utils.py", line 417, in validate_choice_list
    raise UnexpectedValueError((
restfly.errors.UnexpectedValueError: scap1_2export_format has value of pdf.  Expected one of ,v2
>>> 

**Expected behavior**
should be able to export pdf format report

**Screenshots**
NA

**System Information (please complete the following information):**
NA

**Additional context**

**Comment by SteveMcGrath** [comment]
Scan objects cannot be exported in PDF.  You would export a report in PDF format.

**Comment by aseemsavio** [comment]
Closing (as designed).
