### ISSUE TITLE
uuid not match pattern

### ISSUE THREAD

**Issue by ve2tmq** [tenable/pyTenable#629]
**Describe the bug**
When tried to search by uuid, I've got error Does not match pattern, but the pattern is valid.

**To Reproduce**
python3
>>> sc.repositories.asset_intersections(6, 'BF568E73-B7DB-4639-A000-C4F8AF9E0E80')
uuid has value of BF568E73-B7DB-4639-A000-C4F8AF9E0E80.  Does not match pattern ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tenable/sc/repositories.py", line 523, in asset_intersections
    params['uuid'] = self._check('uuid', uuid, 'uuid')
  File "/usr/local/lib/python3.9/site-packages/tenable/base/endpoint.py", line 76, in _check
    return check(name=name,
  File "/usr/local/lib/python3.9/site-packages/restfly/utils.py", line 551, in check
    validate_normalized(obj, validate_regex_pattern,
  File "/usr/local/lib/python3.9/site-packages/restfly/utils.py", line 474, in validate_normalized
    func(arg, obj)
  File "/usr/local/lib/python3.9/site-packages/restfly/utils.py", line 411, in validate_regex_pattern
    raise UnexpectedValueError(
restfly.errors.UnexpectedValueError: uuid has value of BF568E73-B7DB-4639-A000-C4F8AF9E0E80.  Does not match pattern ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$

**System Information (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Architecture 64bit
 - Memory 16 Gb

**Comment by ChadKlunck** [comment]
The pattern as written is case-sensitive. Do you still receive UnexpectedValueError if you use the same uuid, but with lowercase letters?

**Comment by ve2tmq** [comment]
You right!

I pass all day to find this. lol


Ok, my bad.

Thanks
