### ISSUE TITLE
scans.copy is failing

### ISSUE THREAD

**Issue by dainok** [tenable/pyTenable#678]
**Describe the bug**
tio.scans.copy is not working.

**To Reproduce**
1. Create a new scan via WebUI
2. On python run

~~~
tio = TenableIO(
	access_key=access_key,
	secret_key=secret_key,
	url="https://localhost:8834",
	ssl_verify=False,
)

template_scan = tio.scans.list()[0]
tio.scans.copy(template_scan["id"], folder_id=template_scan["folder_id"], name="test")
~~~

**Expected behavior**
Should complete as expected.

**Screenshots**
The following error is returned:

~~~
[412: POST] https://localhost:8834/scans/7/copy body=b''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.10/site-packages/tenable/io/scans.py", line 613, in copy
    return self._api.post('scans/{}/copy'.format(scan_id),
  File "/opt/netbox/venv/lib/python3.10/site-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.PreconditionFailedError: [412: POST] https://localhost:8834/scans/7/copy body=b''
~~~

**System Information (please complete the following information):**
 - OS: Ubuntu bookworm/sid
 - Architecture: x86_64
 - Version: pyTenable==1.4.12
 - Memory: 4G

**Additional context**

It's failing also without name and folder_id:

~~~
tio.scans.copy(template_scan["id"])
[412: POST] https://localhost:8834/scans/7/copy body=b''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.10/site-packages/tenable/io/scans.py", line 613, in copy
    return self._api.post('scans/{}/copy'.format(scan_id),
  File "/opt/netbox/venv/lib/python3.10/site-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.PreconditionFailedError: [412: POST] https://localhost:8834/scans/7/copy body=b''
~~~

**Comment by SteveMcGrath** [comment]
Do not use the TenableIO package for Nessus.  Please look at the Nessus package instead.

https://pytenable.readthedocs.io/en/stable/api/nessus/index.html

**Comment by dainok** [comment]
After googling a lot I found the right answer: https://community.tenable.com/s/question/0D5f200004tDygMCAS/why-is-api-support-being-removed-from-nessus-professional
