### ISSUE TITLE
[Nessus] Unable to export scan - AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by stiong-p** [tenable/pyTenable#694]
Query payload:
```
nessus.scans.export_scan(
        scan_id=7,
        fobj= 'opt/admin/test.nessus')
```

when the query is being ran, it outputs error as follow:

```
python3 nessus.py
Traceback (most recent call last):
  File "nessus.py", line 15, in <module>
    fobj= 'opt/admin/test.nessus')
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/scans.py", line 261, in export_scan
    return self._api.tokens._fetch(token, **dlopts)  # noqa PLW0212
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/tokens.py", line 110, in _fetch
    return self.download(token, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/tokens.py", line 85, in download
    hook_kwargs=hook_kwargs
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/files.py", line 94, in _download
    stream_hook(response, fobj, chunk_size, **hook_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/files.py", line 83, in base_hook
    fobj.write(chunk)
AttributeError: 'str' object has no attribute 'write'
```

I am thinking that I would need to specify stream_hook and/or hook_kwargs but could not find any info on what arguments to include. 

Does anyone have any idea on how this can be resolved?

**Comment by aseemsavio** [comment]
@stiong-p  The `fobj` param takes in a file object. You can pass in a file object into the function like this:

```
with open("new_file_name.nessus", 'w') as nessus_file:
    nessus.scans.export_scan(scan_id=7, fobj=nessus_file)
```

**Comment by stiong-p** [comment]
Thank you for helping on this, @aseemsavio 
After making the changes, it returns with new error: 
TypeError: write() argument must be str, not bytes

```
python3 nessus.py

Traceback (most recent call last):
  File "nessus.py", line 14, in <module>
    nessus.scans.export_scan(scan_id=7, fobj=nessus_file)
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/scans.py", line 261, in export_scan
    return self._api.tokens._fetch(token, **dlopts)  # noqa PLW0212
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/tokens.py", line 110, in _fetch
    return self.download(token, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/tokens.py", line 85, in download
    hook_kwargs=hook_kwargs
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/files.py", line 94, in _download
    stream_hook(response, fobj, chunk_size, **hook_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenable/nessus/files.py", line 83, in base_hook
    fobj.write(chunk)
TypeError: write() argument must be str, not bytes

```

**Comment by aseemsavio** [comment]
It is not necessary to do `nessus_file.write` at your end. pyTenable takes care of it. You can try passing the file object in 'wb' mode like so.

```
with open("new_file_name.nessus", 'wb') as nessus_file:
    nessus.scans.export_scan(scan_id=7, fobj=nessus_file)
```

**Comment by stiong-p** [comment]
Thank you @aseemsavio all good now.
