### ISSUE TITLE
WAS Export function raises: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 1core0** [tenable/pyTenable#861]
**Describe the bug**
As the VM export does not display any WAS finding, I used the export function in the [WAS API](https://pytenable.readthedocs.io/en/stable/api/io/was.html#tenable.io.was.api.WasAPI.export).
The function raises an error stating the object is type of "NoneType" and therefore not subscriptable - even though findings exists on the instance.

**To Reproduce**

```
> ptpython
>>> from tenable.io import TenableIO
>>> tvm = TenableIO()
>>> tvm.was.export()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.13/site-packages/tenable/io/was/api.py", line 61, in export
    parent_scan_ids_with_finalized_at = [_parent_id_with_finalized_at(sc) for sc in scan_config if sc]
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/tenable/io/was/api.py", line 183, in _parent_id_with_finalized_at
    "parent_scan_id": scan_config["last_scan"]["scan_id"],
                      ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**
Fetch Web Application Scan results

**Screenshots**
<img width="682" alt="image" src="https://github.com/user-attachments/assets/3e96b7d7-da8d-4331-8843-8fefb4797cb3" />

**System Information (please complete the following information):**
 - OS: MacOS
 - 64-bit 

**Additional context**

Name: pyTenable
Version: 1.6.0

**Comment by SteveMcGrath** [comment]
The WASv2 APIs will likely go through a larger refactor at some point as they aren't well implemented.

There ARE new was export APIs that 1.6 already supports, but aren't GA quite yet.

https://pytenable.readthedocs.io/en/stable/api/io/exports.html#tenable.io.exports.api.ExportsAPI.was
